// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.roo.inaction.model;

import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.roo.inaction.model.TrainingProgram;
import org.springframework.stereotype.Component;

privileged aspect TrainingProgramDataOnDemand_Roo_DataOnDemand {
    
    declare @type: TrainingProgramDataOnDemand: @Component;
    
    private Random TrainingProgramDataOnDemand.rnd = new SecureRandom();
    
    private List<TrainingProgram> TrainingProgramDataOnDemand.data;
    
    public TrainingProgram TrainingProgramDataOnDemand.getNewTransientTrainingProgram(int index) {
        TrainingProgram obj = new TrainingProgram();
        setName(obj, index);
        return obj;
    }
    
    public void TrainingProgramDataOnDemand.setName(TrainingProgram obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public TrainingProgram TrainingProgramDataOnDemand.getSpecificTrainingProgram(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        TrainingProgram obj = data.get(index);
        return TrainingProgram.findTrainingProgram(obj.getId());
    }
    
    public TrainingProgram TrainingProgramDataOnDemand.getRandomTrainingProgram() {
        init();
        TrainingProgram obj = data.get(rnd.nextInt(data.size()));
        return TrainingProgram.findTrainingProgram(obj.getId());
    }
    
    public boolean TrainingProgramDataOnDemand.modifyTrainingProgram(TrainingProgram obj) {
        return false;
    }
    
    public void TrainingProgramDataOnDemand.init() {
        data = TrainingProgram.findTrainingProgramEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'TrainingProgram' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.roo.inaction.model.TrainingProgram>();
        for (int i = 0; i < 10; i++) {
            TrainingProgram obj = getNewTransientTrainingProgram(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
